services:
  app:
    container_name: banglossOverspeed
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/:/app
    devices:
      - /dev/video0:/dev/video0  # Map the camera device
    environment:
      - DISPLAY=$DISPLAY         # Share display settings (if needed)
    command: python main.py

    stdin_open: true
    tty: true
